FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y \
    curl \
    bzip2 \
    ca-certificates \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# micromamba
ENV MAMBA_ROOT_PREFIX=/opt/conda
RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | \
    tar -xvj bin/micromamba && \
    mv bin/micromamba /usr/local/bin/

WORKDIR /app

COPY environment.yml .
RUN micromamba create -y -f environment.yml && \
    micromamba clean --all --yes

ENV CONDA_DEFAULT_ENV=FCD-meld
ENV PATH=/opt/conda/envs/FCD-meld/bin:$PATH

# COPY meldgraph.sh /app/meldgraph.sh
COPY . .
# RUN dos2unix /app/meldgraph.sh && chmod +x /app/meldgraph.sh

ENV PYTHONPATH=/app

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
